# Generated by Django 5.2.5 on 2025-08-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='chennai', max_length=25),
        ),
    ]
